Update README.md
netbox-community/netbox-floorplan-plugin pull request #13
Opened 2024-03-19 19:56 UTC by pkropf

Added installation note to migrate the database.

2024-04-10 14:12 UTC, jeffgdotorg commented
This PR addresses issue #18

2024-04-10 14:16 UTC, jeffgdotorg requested changes
Thanks for creating this PR. I'll assign #18 to you and merge once requested changes are made.

2024-04-10 14:16 UTC, jeffgdotorg commented on README.md
> +Update the database:
```suggestion
To add the required `netbox_floorplan` tables to your NetBox database, run the `migrate` manager subcommand in the NetBox virtual environment:
```

2024-04-10 14:16 UTC, jeffgdotorg commented on README.md
> +python manage.py migrate netbox_floorplan
```suggestion
cd /opt/netbox
sudo ./venv/bin/python3 netbox/manage.py migrate
```

2024-06-12 22:50 UTC, cruse1977 commented
Closing this as superceded.

2024-06-12 22:50 UTC, closed without merging